---
addPet:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.AddPet.RequestValidator: {}
  handlers:
    - Petstore.Gen.AddPet.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.AddPet.ResponseValidator: {}
updatePet:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.UpdatePet.RequestValidator: {}
  handlers:
    - Petstore.Gen.UpdatePet.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.UpdatePet.ResponseValidator: {}
findPetsByStatus:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.FindPetsByStatus.RequestValidator: {}
  handlers:
    - Petstore.Gen.FindPetsByStatus.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.FindPetsByStatus.ResponseValidator: {}
findPetsByTags:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.FindPetsByTags.RequestValidator: {}
  handlers:
    - Petstore.Gen.FindPetsByTags.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.FindPetsByTags.ResponseValidator: {}
deletePet:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.DeletePet.RequestValidator: {}
  handlers:
    - Petstore.Gen.DeletePet.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.DeletePet.ResponseValidator: {}
getPetById:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.GetPetById.RequestValidator: {}
  handlers:
    - Petstore.Gen.GetPetById.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.GetPetById.ResponseValidator: {}
updatePetWithForm:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.UpdatePetWithForm.RequestValidator: {}
  handlers:
    - Petstore.Gen.UpdatePetWithForm.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.UpdatePetWithForm.ResponseValidator: {}
uploadFile:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.UploadFile.RequestValidator: {}
  handlers:
    - Petstore.Gen.UploadFile.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.UploadFile.ResponseValidator: {}
getInventory:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.GetInventory.RequestValidator: {}
  handlers:
    - Petstore.Gen.GetInventory.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.GetInventory.ResponseValidator: {}
placeOrder:
  preprocessors:
    - Petstore.Gen.PlaceOrder.RequestValidator: {}
  handlers:
    - Petstore.Gen.PlaceOrder.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.PlaceOrder.ResponseValidator: {}
deleteOrder:
  preprocessors:
    - Petstore.Gen.DeleteOrder.RequestValidator: {}
  handlers:
    - Petstore.Gen.DeleteOrder.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.DeleteOrder.ResponseValidator: {}
getOrderById:
  preprocessors:
    - Petstore.Gen.GetOrderById.RequestValidator: {}
  handlers:
    - Petstore.Gen.GetOrderById.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.GetOrderById.ResponseValidator: {}
createUser:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.CreateUser.RequestValidator: {}
  handlers:
    - Petstore.Gen.CreateUser.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.CreateUser.ResponseValidator: {}
createUsersWithArrayInput:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.CreateUsersWithArrayInput.RequestValidator: {}
  handlers:
    - Petstore.Gen.CreateUsersWithArrayInput.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.CreateUsersWithArrayInput.ResponseValidator: {}
createUsersWithListInput:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.CreateUsersWithListInput.RequestValidator: {}
  handlers:
    - Petstore.Gen.CreateUsersWithListInput.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.CreateUsersWithListInput.ResponseValidator: {}
loginUser:
  preprocessors:
    - Petstore.Gen.LoginUser.RequestValidator: {}
  handlers:
    - Petstore.Gen.LoginUser.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.LoginUser.ResponseValidator: {}
logoutUser:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.LogoutUser.RequestValidator: {}
  handlers:
    - Petstore.Gen.LogoutUser.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.LogoutUser.ResponseValidator: {}
deleteUser:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.DeleteUser.RequestValidator: {}
  handlers:
    - Petstore.Gen.DeleteUser.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.DeleteUser.ResponseValidator: {}
getUserByName:
  preprocessors:
    - Petstore.Gen.GetUserByName.RequestValidator: {}
  handlers:
    - Petstore.Gen.GetUserByName.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.GetUserByName.ResponseValidator: {}
updateUser:
  preprocessors:
    - Quenya.Plug.JwtPlug: {}
    - Petstore.Gen.UpdateUser.RequestValidator: {}
  handlers:
    - Petstore.Gen.UpdateUser.FakeHandler: {}
  postprocessors:
    - Petstore.Gen.UpdateUser.ResponseValidator: {}
